name: Convert SRT to Plain TXT

on:
  push:
    paths:
      - '**/*.srt'

jobs:
  convert-srt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Convert SRT files to TXT
        run: |
          find . -name "*.srt" | while IFS= read -r file; do
            txt_file="${file%.srt}.txt"
            awk '
              /^[0-9]+$/ { next }
              /^[0-9]{2}:[0-9]{2}:[0-9]{2},/ { next }
              NF { gsub(/\r/, ""); printf "%s ", $0 }
            ' "$file" | awk 'BEGIN{ORS=" "} {print}' | sed 's/  */ /g' > "$txt_file"
          done



      - name: Commit converted TXT files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Convert SRT files to plain TXT" || echo "No changes to commit"
          git push

    permissions:
      contents: write
