name: Convert SRT to Plain TXT in All Folders

on:
  push:
    paths:
      - '**/*.srt'

permissions:
  contents: write

jobs:
  convert-srt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Convert SRT files to TXT
        run: |
          find . -type f -name "*.srt" | while IFS= read -r file; do
            txt_file="${file%.srt}.txt"
            awk '
              /^[0-9]+$/ { next }
              /^[0-9]{2}:[0-9]{2}:[0-9]{2},[0-9]{3} -->/ { next }
              NF { gsub(/\r/, ""); printf "%s ", $0 }
            ' "$file" | sed -E 's/ ([0-9]+) /\ /g' | sed 's/  */ /g' > "$txt_file"
          done

      - name: Commit converted TXT files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Convert SRT to TXT in all folders" || echo "No changes to commit"
          git push
