name: Convert SRT to Plain TXT

on:
  push:
    paths:
      - '**/*.srt'

jobs:
  convert-srt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Find and convert all SRT files
        run: |
          find . -name "*.srt" | while read file; do
            txt_file="${file%.srt}.txt"
            sed -E '/^[0-9]+$/d;/^([0-9]{2}:){2}[0-9]{2},[0-9]{3} -->/d;/^$/d' "$file" \
              | paste -sd ' ' - > "$txt_file"
          done

      - name: Commit converted TXT files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Convert SRT files to plain TXT" || echo "No changes to commit"
          git push
    permissions:
      contents: write
